### ISSUE TITLE
USER STORY:Matching label size with paper size

### ISSUE THREAD

**Issue by Charly1357** [Charly1357/My-third-Agile-Project#2]
As a **warehouse operator**  I can **select the paper size on which to print**  so that **the printed label size matches the parcel size**

**Comment by Charly1357** [comment]
In order to provide my opinion to a certain running topic I can select and submit an answer from the poll

**Comment by Charly1357** [comment]
In order to provide additonal answer I can add a comment before I submit my poll response

**Comment by Charly1357** [comment]
In order to collect users feedback as an administrator I can publish a poll

**Comment by Charly1357** [comment]
In order to automatically hide the poll as an administrator I can pick the expiry date while publishing the poll

**Comment by Charly1357** [comment]
***Acceptance Criteria:***
  * a)The option should be provided as a checkbox
  * b)The checkbox should be checked by default
  * c)The option should appear next to the submit button
  
***Tasks***
   * [ ] Update the view the poll design(HTML and CSS) to include the checkbox and 
   to show the name of the submitter
   * [ ] Create a new field in the model to track the username
   * [ ] Update the controller function
   * [ ] Update unit test scripts
   * [ ] Test the functionality

**Comment by Charly1357** [comment]
***User story:*** In order to automatically hide the poll as an administrator,I can pick the expire date while publishing the poll

***Acceptance Criteria:***
   * a.The poll should disappear at 11:59 pm on the target date
   * b.The real estate of "Poll should be reserved on the home page, a message that says "Stayed tuned,a 
   new poll is coming soon
   * c.The administrator expire date should be at least 3 days after the current date.
   
***Tasks:***
  * [ ] Update the admin module view:the poll design (HTML and CSS) to include date picker
  * [ ] Update the website view show "Stay tuned, a new poll is coming soon
  * [ ] Create Javascript function to validate the expiry date is at least after 3 days
  * [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
  * [ ] Update unit test scripts
  * [ ] Test the functionality
